language: java
install:
# Invoke the "travis" profile during Maven steps; see <profile> in pom.xml
# files. The "mvn install" command will run by default during the "install"
# phase by Travis, without the profile flag. Here we customize the install
# phase to use the relevant profile.
# https.protocols is a workaround for https://bugs.openjdk.java.net/browse/JDK-8213202
- mvn install -P test -DskipTests=true -Dmaven.javadoc.skip=true -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2 -B -V
script:
- mvn test -P test -B
